/**
 * Forms Configuration Registry
 * 
 * STATIC CONFIGURATION - Do NOT auto-create forms
 * User will manually provide Google Form URLs
 * 
 * IMPORTANT:
 * - Google Forms are the ONLY member-facing input
 * - Forms feed into Google Sheets (source of truth)
 * - Dashboard is STAFF-ONLY (read-only from sheets)
 */

export interface FormConfig {
  id: string;
  name: string;
  description: string;
  targetSheet: string;
  category: 'membership' | 'guest' | 'volunteer' | 'donation' | 'support';
  icon: string; // Lucide icon name
  formUrl: string; // Google Form URL - TO BE PROVIDED BY USER
  responseSheetUrl: string; // Google Sheets responses URL
  status: 'active' | 'pending' | 'inactive';
  requiredFields: string[];
  instructions: string;
}

/**
 * Pre-configured forms for TCC CRM
 * 
 * ACTION REQUIRED:
 * User must manually create these Google Forms and provide URLs
 */
export const FORM_REGISTRY: FormConfig[] = [
  {
    id: 'member-registration',
    name: 'New Member Registration',
    description: 'Primary registration form for new church members',
    targetSheet: 'Members',
    category: 'membership',
    icon: 'UserPlus',
    formUrl: 'https://forms.gle/Ew8mCmCetxDCvQco6',
    responseSheetUrl: '', // ⚠️ Automatically generated by Google Forms
    status: 'active',
    requiredFields: [
      'First Name',
      'Surname/Last Name',
      'Email Address',
      'Phone Number',
      'Date of Birth',
      'Gender',
      'Home Address'
    ],
    instructions: `
      1. Go to Google Forms (https://forms.google.com)
      2. Create a new form titled "TCC Member Registration"
      3. Add these fields in ORDER:
         - First Name (Short answer, Required)
         - Surname/Last Name (Short answer, Required)
         - Other Names (Short answer, Optional)
         - Email Address (Short answer, Required, Email validation)
         - Phone Number (Short answer, Required)
         - Date of Birth (Date, Required)
         - Gender (Multiple choice: Male, Female, Required)
         - Marital Status (Multiple choice: Single, Married, Widowed)
         - Home Address (Paragraph, Required)
         - City (Short answer, Required)
         - State (Dropdown: Lagos, Abuja, etc.)
         - Nationality (Short answer, Default: "Nigerian")
         - Occupation (Short answer, Optional)
         - How did you hear about us? (Paragraph, Optional)
      4. Connect to Google Sheets: Responses → Create Spreadsheet → Link to existing "Members" sheet
      5. Copy the form URL and paste it here
    `
  },
  {
    id: 'guest-registration',
    name: 'Guest/First-Time Visitor',
    description: 'Quick registration for guests and first-time visitors',
    targetSheet: 'Guest',
    category: 'guest',
    icon: 'UserCheck',
    formUrl: 'https://forms.gle/Lf3F7jrvYjSyfBXF9',
    responseSheetUrl: '',
    status: 'active',
    requiredFields: [
      'First Name',
      'Last Name',
      'Phone Number',
      'Email',
      'Visit Date'
    ],
    instructions: `
      1. Create Google Form: "TCC Guest Registration"
      2. Add fields:
         - First Name (Short answer, Required)
         - Last Name (Short answer, Required)
         - Phone Number (Short answer, Required)
         - Email (Short answer, Optional)
         - Invited By (Short answer, Optional)
         - How did you hear about us? (Dropdown: Friend/Family, Social Media, Website, Walk-in)
         - Would you like to receive updates? (Multiple choice: Yes, No)
      3. Link to "Guest" sheet
      4. Copy form URL
    `
  },
  {
    id: 'volunteer-signup',
    name: 'Volunteer Signup',
    description: 'Register for volunteer roles and departments',
    targetSheet: 'VolunteerAssignments',
    category: 'volunteer',
    icon: 'Heart',
    formUrl: 'https://forms.gle/eYHALTc3njMzJaMz8',
    responseSheetUrl: '',
    status: 'active',
    requiredFields: [
      'Full Name',
      'Member ID',
      'Phone Number',
      'Preferred Department'
    ],
    instructions: `
      1. Create Google Form: "TCC Volunteer Signup"
      2. Add fields:
         - Full Name (Short answer, Required)
         - Member ID (Short answer, Optional - for existing members)
         - Phone Number (Short answer, Required)
         - Email (Short answer, Required)
         - Department of Interest (Checkboxes: Ushering, Media, Children's Ministry, Choir, Hospitality, etc.)
         - Availability (Checkboxes: Sundays, Wednesdays, Fridays, Special Events)
         - Skills/Experience (Paragraph, Optional)
         - Why do you want to volunteer? (Paragraph, Required)
      3. Link to "VolunteerAssignments" sheet
      4. Copy form URL
    `
  },
  {
    id: 'donation-form',
    name: 'Donation/Giving Form',
    description: 'Record tithes, offerings, and special donations',
    targetSheet: 'Donations',
    category: 'donation',
    icon: 'DollarSign',
    formUrl: '', // ⚠️ USER MUST PROVIDE
    responseSheetUrl: '',
    status: 'pending',
    requiredFields: [
      'Full Name',
      'Member ID',
      'Amount',
      'Donation Type',
      'Payment Method'
    ],
    instructions: `
      1. Create Google Form: "TCC Donation Form"
      2. Add fields:
         - Full Name (Short answer, Required)
         - Member ID (Short answer, Optional)
         - Phone Number (Short answer, Required)
         - Amount (Short answer, Required, Number validation)
         - Currency (Multiple choice: NGN, USD, Required, Default: NGN)
         - Donation Type (Dropdown: Tithe, Offering, Building Fund, Mission, Welfare, Special Seed)
         - Payment Method (Dropdown: Cash, Bank Transfer, Card, Check)
         - Date of Donation (Date, Required)
         - Transaction Reference (Short answer, Optional)
         - Anonymous Donation? (Multiple choice: Yes, No, Default: No)
      3. Link to "Donations" sheet
      4. Copy form URL
      
      ⚠️ SECURITY: For bank transfers, provide bank details in form description
    `
  },
  {
    id: 'prayer-request',
    name: 'Prayer Request',
    description: 'Submit prayer requests and testimonies',
    targetSheet: 'SupportRequests',
    category: 'support',
    icon: 'MessageSquare',
    formUrl: 'https://forms.gle/sCxiVK9MfqDPPP4S8',
    responseSheetUrl: '',
    status: 'active',
    requiredFields: [
      'Name',
      'Request Type',
      'Message'
    ],
    instructions: `
      1. Create Google Form: "TCC Prayer Request"
      2. Add fields:
         - Name (Short answer, Required)
         - Phone Number (Short answer, Optional)
         - Email (Short answer, Optional)
         - Request Type (Multiple choice: Prayer Request, Testimony, Counseling, Other)
         - Message (Paragraph, Required)
         - Would you like pastoral follow-up? (Multiple choice: Yes, No)
         - Confidential? (Multiple choice: Yes, No, Default: No)
      3. Link to "SupportRequests" sheet
      4. Copy form URL
    `
  }
];

/**
 * Get form by ID
 */
export function getFormById(id: string): FormConfig | undefined {
  return FORM_REGISTRY.find(form => form.id === id);
}

/**
 * Get active forms
 */
export function getActiveForms(): FormConfig[] {
  return FORM_REGISTRY.filter(form => form.status === 'active');
}

/**
 * Get forms by category
 */
export function getFormsByCategory(category: FormConfig['category']): FormConfig[] {
  return FORM_REGISTRY.filter(form => form.category === category);
}

/**
 * Update form URL (to be called from Forms Manager UI)
 */
export function updateFormUrl(id: string, formUrl: string, responseSheetUrl?: string): boolean {
  const form = getFormById(id);
  if (!form) return false;
  
  form.formUrl = formUrl;
  if (responseSheetUrl) {
    form.responseSheetUrl = responseSheetUrl;
  }
  form.status = formUrl ? 'active' : 'pending';
  
  return true;
}

/**
 * Validate if form is ready to use
 */
export function isFormReady(id: string): boolean {
  const form = getFormById(id);
  return form ? (form.status === 'active' && form.formUrl.length > 0) : false;
}

/**
 * Get form setup progress
 */
export function getSetupProgress(): {
  total: number;
  completed: number;
  pending: number;
  percentage: number;
} {
  const total = FORM_REGISTRY.length;
  const completed = FORM_REGISTRY.filter(f => f.status === 'active').length;
  const pending = FORM_REGISTRY.filter(f => f.status === 'pending').length;
  
  return {
    total,
    completed,
    pending,
    percentage: Math.round((completed / total) * 100)
  };
}
